config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/signup" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  
  devise_for :users, :controllers => {registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "callbacks"}

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'disclaimer', to: 'pages#disclaimer'

  
  resources :exercises do
    member do
      put "like", to: "exercises#upvote"
      put "dislike", to: "exercises#downvote"
    end
    resources :variations do
      get ':id/edit' => "variations#edit"
      get 'new' => "variations#new"
    end
  end
  
  resources :routines
  resources :categories
  resources :muscle_groups
  resources :blogs
  resources :administrators
  resources :dashboard
  
  resources :feedbacks, only: [:create, :show, :edit, :update, :destroy]
  
  get 'your_feedback' => "feedbacks#new"
  get 'feedback/dashboard' => "feedbacks#index"
  
  resources :contacts, only: [:create]
  get 'contact' => "contacts#new"
  
  
  

end

app/models/routine.rb
class Routine < ActiveRecord::Base
  belongs_to :user
  has_many :routine_exercises
  has_many :exercises, through: :routine_exercises
  
  accepts_nested_attributes_for :routine_exercises, :allow_destroy => true
  accepts_nested_attributes_for :exercises
  
  validates :title, presence: true, length: { minimum: 3 }
  validates :difficulty, presence: true
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def index
    @routines = Routine.paginate(page: params[:page], per_page: 10)
  end
  
  def new
    if current_user.nil?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      @routine = Routine.new
    end
  end
  
  def create
    @routine = Routine.new(routine_params)
    @routine.user = current_user
    if @routine.save
      flash[:success] = "Exercise has been created"
      redirect_to routines_path
    else
      flash.now[:danger] = "Exercise has not been created"
      render :new
    end
  end
  
  def show
    @routine = Routine.find(params[:id])
  end
  
  def edit
    @routine = Routine.find(params[:id])
  end
  
  def update
    @routine = Routine.find(params[:id])
    if @routine.update(routine_params)
      flash[:success] = "Workout routine has been successfully updated"
      redirect_to routine_path(@routine)
    else
      render :edit
    end
  end
  
  def destroy
    @routine = Routine.find(params[:id])
    if @routine.destroy
      flash[:success] = "Workout Routine has been deleted"
      redirect_to rotuines_path
    else
      render :edit
    end
  end
  
  private
    def routine_params
      params.require(:routine).permit(:title, :description, :difficulty, 
          :routine_exercises_attributes => [:id, :exercise, :exercise_id, :routine_id, :sets, :reps, :_destroy])
    end
end

app/views/routines/_form.html.erb
<%= render 'shared/errors', obj: @routine %>

<div class="row">
  <div class="col-lg-6">
    <%= simple_form_for @routine do |f| %>
      <div class="form-group">
        <%= f.input :title %>
        <%= f.input :difficulty, collection: ["Easy", "Intermediate", "Hard"], prompt: "Select Difficulty" %>
        <%= f.input :description, as: :text %>
      </div>
      
      <!-- Exercises -->
      <div class="form-group">
        <div id="routine-exercises">
          <%= f.simple_fields_for :routine_exercises do |routine_exercise| %>
            <%= render 'routine_exercise_fields', f: routine_exercise %>
          <% end %>
        </div>
        <div class="links">
          <%= link_to_add_association 'Add Exercise', f, :routine_exercises, 
                  :class => "btn btn-primary", 
                  'data-association-insertion-node' => "#routine-exercises",
                  'data-association-insertion-method' => "append",
                  :wrap_object => Proc.new { |re| re.build_exercise; re } %>
        </div>
      </div>
      <!-- End of Exercises -->
        
      <div class="form-group">
        <%= f.button :submit, class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/routines/_routine_exercise_fields.html.erb
<div class="nested-fields routine-exercise-fields">
  <div class="exercise_from_list">
    <%= f.association :exercise, collection: Exercise.order(:name), prompt: 'Select Exercise', input_html: { class: 'exercise-selectize' }%>
    <%= f.input :sets %>
    <%= f.input :reps %>
  </div>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/routines/edit.html.erb
<h1>Edit Workout Routine</h1>

<%= render 'form' %>

app/views/routines/index.html.erb
<div class="container">
<h1>Routines</h1>

<% if user_signed_in? %>
  <%= link_to "Create New Routine", new_routine_path() %>
<% end %>

<% @routines.each do |routine| %>
  <div class="row">
    <div class="blog-container col-md-8">
      <h3><%= link_to routine.title, routine_path(routine) %></h3>
      <p>
        <%= routine.description %>
      </p>
    </div>
  </div>

<% end %>

<!-- Add this to paginate your page, given the pagination details -->
<%= will_paginate %>
</div>

app/views/routines/new.html.erb
<h1>Create New Workout Routine</h1>

<%= render 'form' %>

app/views/routines/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="routine-heading"><%= @routine.title %></h1>
  </div>

  <div class="row col-lg-6 col-lg-offset-3">
    <div class="routine-description">
      <p><%= @routine.description %></p>
      <p>Difficulty: <%= @routine.difficulty %></p>
    </div>

    <div class="routine-outline">
      <% if @routine.exercises.any? %>
        <table class="table">
          <thead>
            <th>Exercise</th>
            <th>Sets</th>
            <th>Reps</th>
          </thead>
          <tbody>
            <% @routine.routine_exercises.includes(:exercise).each do |routine_exercise| %>
              <tr>
                <td><%= link_to routine_exercise.exercise.name, exercise_path(routine_exercise.exercise) %></td>
                <td><%= routine_exercise.sets %></td>
                <td><%= routine_exercise.reps %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
      <% end %>
    </div>
  
  </div>


  <% if user_signed_in? && current_user == @routine.user %>
    <%= link_to "Edit Routine", edit_routine_path(@routine), class: "btn btn-primary btn-space" %>
    <%= link_to "Delete Routine", blog_path(@routine), method: :delete, 
              data: { confirm: "Are you sure you want to delete the Workout Routine?" },
              class: "btn btn-danger btn-primary btn-space" %>
  <% end %>
</div>