config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/signup" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  
  devise_for :users, :controllers => {registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "callbacks"}

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'disclaimer', to: 'pages#disclaimer'

  
  resources :exercises do
    member do
      put "like", to: "exercises#upvote"
      put "dislike", to: "exercises#downvote"
    end
    resources :variations do
      get ':id/edit' => "variations#edit"
      get 'new' => "variations#new"
    end
  end
  
  resources :routines
  resources :categories
  resources :muscle_groups
  resources :blogs
  resources :administrators
  resources :dashboard
  
  resources :feedbacks, only: [:create, :show, :edit, :update, :destroy]
  
  get 'your_feedback' => "feedbacks#new"
  get 'feedback/dashboard' => "feedbacks#index"
  
  resources :contacts, only: [:create]
  get 'contact' => "contacts#new"
  
  
  

end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 footer-link-container">
        <h5>Important</h5>
        <ul>
          <li><%= link_to "Disclaimer", '/disclaimer' %></li>
        </ul>
      </div>
      <div class="col-lg-4 footer-link-container">
        <h5>Get To Know Us</h5>
        <ul>
          <li><%= link_to "About", '/about' %></li>
          <li><%= link_to "Blog", blogs_path %></li>
        </ul>
      </div>
      <div class="col-lg-4 footer-link-container">
        <h5>Contact Us</h5>
        <ul>
          <li><%= link_to "Contact", '/contact' %></li>
          <li>
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li>
                  <%= link_to feedback_dashboard_path do %>
                    Feedback <%= content_tag :span, Feedback.where(:actioned => false).count, class: 'badge' %>
                  <% end %>
                </li>
              <% end %>
              <% else %>
                <li><%= link_to "Feedback", your_feedback_path %></li>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row copyright">
    <div class="container">
      <p><span class="copyright">Copyright 2017 &copy; Skolpt</span></p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("Logo_65px_height.png", :border => 0, :alt => 'Skolpt', :title => 'Skolpt'), root_path, class: "navbar-brand" %>
      </div>

      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        
        <!-- Root path currently links to Exercises. Not required at this time
        <ul class="nav navbar-nav">
          <li><%= link_to "Exercises", root_path %></li>
        </ul>
        -->
        
        <!-- Search form -->
        <!--
        <ul class="nav navbar-nav navbar-left">
          <%= form_tag(exercises_path, :method => "get", class: "navbar-form navbar-left") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Exercises", class: 'form-control' %>
          <% end %>
        </ul>
        -->
        <!-- End Search Form -->
        
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Routines", routines_path() %></li>
          <li><%= link_to "Exercises", exercises_path() %></li>
          
          <!--
          Blocked out until filter can be applied
          
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Exercises <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Strength", exercises_path(), class: "bold", @title => "All Exercises" %></li>
              <li><%= link_to "Abdomen", exercises_path(:muscle_groups_id=>"7"), :title => "Abdomen Exercises" %></li>
              <li><%= link_to "Arms", exercises_path(:muscle_groups_id=>"2"), @title => "Arm Exercises" %></li>
              <li><%= link_to "Back", exercises_path(:muscle_groups_id=>"4") %></li>
              <li><%= link_to "Buttocks", exercises_path(:muscle_groups_id=>"6") %></li>
              <li><%= link_to "Chest", exercises_path(:muscle_groups_id=>"1") %></li>
              <li><%= link_to "Legs", exercises_path(:muscle_groups_id=>"5") %></li>
              <li><%= link_to "Shoulders", exercises_path(:muscle_groups_id=>"3") %></li>
              <li role="separator" class="divider"></li>
              <li class="bold"><%= link_to "Cardio", exercises_path(), class: "bold" %></li>
              <li role="separator" class="divider"></li>
              <li class="bold"><%= link_to "Stretching", exercises_path(), class: "bold" %></li>
            </ul>
          </li>
          -->
          
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <h6 class="dropdown-header"> Create </h6>
                  <li> <%= link_to "New Exercise", new_exercise_path %> </li>
                  <li> <%= link_to "New Category", new_category_path %> </li>
                  <li> <%= link_to "New Muscle Group", new_muscle_group_path %> </li>
                  <li> <%= link_to "New Blog Post", new_blog_path %> </li>
                  <li role="separator" class="divider"></li>
                  <h6 class="dropdown-header"> View </h6>
                  <li> <%= link_to "Categories", categories_path %> </li>
                  <li> <%= link_to "Muscle Groups", muscle_groups_path %> </li>
                  <li> <%= link_to "Administration", administrators_path %> </li>
                </ul>
              </li>
            <% end %>
          <% end %>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", dashboard_path(current_user) %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                  </ul>
              </li>
          <% end %>
          
          <% if !user_signed_in? %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>

        </ul>
      </div>
    
  </nav>
  
</header>

app/views/shared/_main.html.erb
<%= render 'layouts/messages' %>
<%= yield %>