config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/signup" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  
  devise_for :users, :controllers => {registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "callbacks"}

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'disclaimer', to: 'pages#disclaimer'

  
  resources :exercises do
    member do
      put "like", to: "exercises#upvote"
      put "dislike", to: "exercises#downvote"
    end
    resources :variations do
      get ':id/edit' => "variations#edit"
      get 'new' => "variations#new"
    end
  end
  
  resources :routines
  resources :categories
  resources :muscle_groups
  resources :blogs
  resources :administrators
  resources :dashboard
  
  resources :feedbacks, only: [:create, :show, :edit, :update, :destroy]
  
  get 'your_feedback' => "feedbacks#new"
  get 'feedback/dashboard' => "feedbacks#index"
  
  resources :contacts, only: [:create]
  get 'contact' => "contacts#new"
  
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  
  has_many :exercises
  default_scope { order(name: :asc)}
end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_action :authenticate_user!
  before_filter :set_category, only: [:show, :update, :edit, :destroy]
  
   def index
     if !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      @categories = Category.all
    end
  end
  
  def new
    if current_user.nil? || !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      @category = Category.new
    end
  end
  
  def show
    if !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      @category = Category.find(params[:id])
    end 
  end
  
  def create
    @category = Category.new(params.require(:category).permit(:name, :description))
    if @category.save
      flash[:success] = "Category has been created"
      redirect_to categories_path
    else
      flash.now[:danger] = "Category has not been created"
      render :new
    end
  end
  
  def edit
    if current_user.nil? || !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    end
  end 
  
  def update
    if !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      if @category.update(category_params)
          flash[:success] = "Category has been updated"
          redirect_to @category
      else
        flash.now[:danger] = "Category has not been updated"
        render :edit
      end
    end
  end
  
  def destroy
    if @category.destroy
      flash[:success] = "Category has been deleted"
      redirect_to categories_path
    end
  end
  
  private 
    def category_params
      params.require(:category).permit(:name, :description)
    end
    
    def set_category
    @category=Category.find(params[:id])
    end
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<div class='row'>
  <div class='col-md-12'>
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class='form-group'>
        <div class='control-label col-md-1'>
          <%= f.label :name %>
        </div>
        <div class='col-md-11'>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name of category', autofocus: true %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-md-1'>
          <%= f.label :description %>
        </div>
        <div class='col-md-11'>
          <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Description of category' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='col-md-offset-1 col-md-11'>
          <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h3 class='text-center'>Editing a Category</h3>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% @categories.each do |category| %>
  <div class="well well-lg">
    <div class="category-name">
      <%= link_to category.name, category_path(category) %>
    </div> 
    <div class="category-description">
      <%= truncate(category.description, length: 500) %>
    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<h3 class='text-center'> Add A New Category</h3>

<%= render 'form' %>

app/views/categories/show.html.erb
<category class="detail-category">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <h1 class="category-detail-name"><%= @category.name %></h1>

  <h2 class="category-detail-description">  Description</h2>
  <div class="category-description">
    <%= @category.description %>
  </div>
  
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to "Edit Category", edit_category_path(@category), class: "btn btn-primary btn-lg btn-space" %>
    <%= link_to "Delete Category", category_path(@category), method: :delete, 
              data: { confirm: "Are you sure you want to delete the category?" },
              class: "btn btn-danger btn-primary btn-lg btn-space" %>
  <% end %>
</article>

<hr>