config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/signup" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  
  devise_for :users, :controllers => {registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "callbacks"}

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'disclaimer', to: 'pages#disclaimer'

  
  resources :exercises do
    member do
      put "like", to: "exercises#upvote"
      put "dislike", to: "exercises#downvote"
    end
    resources :variations do
      get ':id/edit' => "variations#edit"
      get 'new' => "variations#new"
    end
  end
  
  resources :routines
  resources :categories
  resources :muscle_groups
  resources :blogs
  resources :administrators
  resources :dashboard
  
  resources :feedbacks, only: [:create, :show, :edit, :update, :destroy]
  
  get 'your_feedback' => "feedbacks#new"
  get 'feedback/dashboard' => "feedbacks#index"
  
  resources :contacts, only: [:create]
  get 'contact' => "contacts#new"
  
  
  

end

app/models/muscle_group.rb
class Muscle_group < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  
  has_many :exercises
  default_scope { order(name: :asc)}
end 

app/controllers/muscle_groups_controller.rb
class MuscleGroupsController < ApplicationController
  #before_action :authenticate_user!
  before_filter :set_muscle_group, only: [:show, :update, :edit, :destroy]
  
  def index
    if !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      @muscle_groups = Muscle_group.all
    end
  end
  
  def new
    if current_user.nil? || !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      @muscle_group = Muscle_group.new
    end
  end
  
  def show
    if !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      @muscle_groups = Muscle_group.find(params[:id])
    end 
  end
  
  def create
    @muscle_groups = Muscle_group.new(params.require(:muscle_group).permit(:name, :description))
    if @muscle_groups.save
      flash[:success] = "Category has been created"
      redirect_to muscle_groups_path
    else
      flash.now[:danger] = "Category has not been created"
      render :new
    end
  end
  
  def edit
    if current_user.nil? || !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    end
  end 
  
  def update
    if !current_user.admin?
      flash[:danger] = "You do not have the permissions to view that page"
      redirect_to root_path
    else
      if @muscle_group.update(muscle_group_params)
          flash[:success] = "Category has been updated"
          redirect_to @muscle_group
      else
        flash.now[:danger] = "Category has not been updated"
        render :edit
      end
    end
  end
  
  private 
    def muscle_group_params
      params.require(:muscle_group).permit(:name, :description)
    end
    
    def set_muscle_group
    @muscle_group=Muscle_group.find(params[:id])
    end
end

app/views/muscle_groups/_form.html.erb
<%= render 'shared/errors', obj: @muscle_group %>

<div class='row'>
  <div class='col-lg-6 col-lg-offset-3'>
    <%= simple_form_for @muscle_group do |f| %>
      <div class="form-group">
        <%= f.input :name %>
        <%= f.input :description, as: :text %>
      </div>
        
      <div class="form-group">
        <%= f.button :submit, class: "btn btn-success" %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/muscle_groups/edit.html.erb
<h3 class='text-center'>Editing <%= @muscle_group.name %></h3>

<%= render 'form' %>

app/views/muscle_groups/index.html.erb
<div class="container">

<h1>All Muscle Groups</h1>

<%= link_to "New Muscle Group", new_muscle_group_path, class: "btn btn-primary btn-space btn-xs" %>

<% @muscle_groups.each do |muscle_group| %>
  <div class="well well-lg">
    <div class="muscle_group-name">
      <%= link_to muscle_group.name, muscle_group_path(muscle_group) %>
    </div> 
    <div class="muscle_group-description">
      <%= truncate(muscle_group.description, length: 500) %>
    </div>
  </div>
<% end %>

</div>

app/views/muscle_groups/new.html.erb
<h3 class='text-center'>New Muscle Group</h3>

<%= render 'form' %>

app/views/muscle_groups/show.html.erb
<div class="container">
  <div class="row col-lg-6 col-lg-offset-3">
    <h1 class=""><%= @muscle_group.name %></h1>
  </div>
  
  <div class="row col-lg-6 col-lg-offset-3">
    <div class="">
      <p><%= @muscle_group.description %></p>
    </div>
  
  </div>

  <div class="row col-lg-6 col-lg-offset-3">
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to "Edit Muscle Group", edit_muscle_group_path(@muscle_group), class: "btn btn-primary btn-space btn-xs" %>
    <%= link_to "Delete Muscle Group", muscle_group_path(@muscle_group), method: :delete, 
              data: { confirm: "Are you sure you want to delete this Muscle Group?" },
              class: "btn btn-danger btn-xs btn-space" %>
  <% end %>
  </div>
  
  <div class="row col-lg-6 col-lg-offset-3">
    <%= link_to "Back to Muscle Groups", muscle_groups_path %>  
  </div>
  
</div>